"""
LUNARA: Scientific Candidate Feature Extractor
Detects lunar impact crater morphologies, linear ridges, and boulder clusters with
sub-pixel coordinates, diameter estimation, confidence, and scientific verification flags.
"""

import numpy as np
import cv2

class ScientificFeatureDetector:
    def __init__(self):
        self.disclaimer = (
            "SCIENTIFIC NOTICE: Extracted features are AI-detected candidate morphologies "
            "generated by the LUNARA prototype pipeline. They require independent planetary "
            "cartographic and peer-reviewed verification before scientific confirmation."
        )

    def detect_features(
        self,
        enhanced_img: np.ndarray,
        confidence_map: np.ndarray,
        risk_map: np.ndarray,
        center_lat: float,
        center_lon: float,
        res_meters: float = 0.5
    ) -> list:
        """
        Detects impact crater rims, circular morphology candidates, and ridge structures.
        Computes physical diameter (km), sub-pixel position, coordinates, confidence, and risk.
        """
        h, w = enhanced_img.shape[:2]
        
        # Preprocessing: Multi-scale edge gradient filtering
        blurred = cv2.GaussianBlur(enhanced_img, (7, 7), 1.5)
        
        # Hough Circles Detection tuned for lunar impact morphologies
        circles = cv2.HoughCircles(
            blurred,
            cv2.HOUGH_GRADIENT,
            dp=1.2,
            minDist=28,
            param1=65,
            param2=30,
            minRadius=8,
            maxRadius=int(min(h, w) * 0.45)
        )
        
        features = []
        feature_id = 1
        
        # Lunar planetary coordinate conversion constants
        # 1 degree of lunar latitude ~= 30.32 km (Moon radius = 1737.4 km)
        km_per_deg_lat = 30.32
        km_per_deg_lon = 30.32 * np.cos(np.radians(center_lat))
        
        if circles is not None:
            circles = np.uint16(np.around(circles))
            for i in circles[0, :]:
                cx, cy, r = int(i[0]), int(i[1]), int(i[2])
                
                # Check image bounds
                if cx < 0 or cx >= w or cy < 0 or cy >= h:
                    continue
                    
                # Physical diameter calculation in meters and kilometers
                diameter_meters = float(r * 2 * res_meters)
                diameter_km = round(diameter_meters / 1000.0, 3)
                
                # Calculate geographic coordinates
                # Offset in pixels relative to center
                offset_x_m = (cx - w / 2.0) * res_meters
                offset_y_m = (h / 2.0 - cy) * res_meters # Invert y for latitude
                
                feat_lat = round(center_lat + (offset_y_m / 1000.0) / km_per_deg_lat, 5)
                feat_lon = round(center_lon + (offset_x_m / 1000.0) / (km_per_deg_lon if abs(km_per_deg_lon) > 1e-4 else 1.0), 5)
                
                # Sample local confidence and risk
                y_min, y_max = max(0, cy - r), min(h, cy + r)
                x_min, x_max = max(0, cx - r), min(w, cx + r)
                
                local_conf = float(np.mean(confidence_map[y_min:y_max, x_min:x_max]) * 100.0)
                local_risk = float(np.mean(risk_map[y_min:y_max, x_min:x_max]) * 100.0)
                
                # Depth-to-diameter ratio estimate (typical lunar fresh simple crater d/D ~ 0.15 - 0.20)
                interior_val = float(np.mean(enhanced_img[max(0, cy - r//2):min(h, cy + r//2), max(0, cx - r//2):min(w, cx + r//2)]))
                rim_val = float(np.mean(enhanced_img[y_min:y_max, x_min:x_max]))
                contrast_ratio = max(0.05, min(0.35, abs(rim_val - interior_val) / 255.0))
                est_depth_m = round(diameter_meters * (0.12 + contrast_ratio * 0.4), 1)
                
                # Assign status classification
                if local_conf >= 80.0 and local_risk <= 20.0:
                    status = "Candidate Crater (High Confidence)"
                    verification_level = "Tier 1: High Scientific Plausibility"
                elif local_conf >= 60.0:
                    status = "AI-Detected Feature (Moderate Confidence)"
                    verification_level = "Tier 2: Requires Photometric Cross-Check"
                else:
                    status = "Candidate Feature (Requires Verification)"
                    verification_level = "Tier 3: Possible Illumination Artifact"

                features.append({
                    "id": f"LUN-FT-{feature_id:03d}",
                    "type": "Impact Crater Morphology",
                    "label": "Candidate crater",
                    "status": status,
                    "verification_requirement": "Requires scientific verification",
                    "verification_tier": verification_level,
                    "pixel_x": cx,
                    "pixel_y": cy,
                    "pixel_radius": r,
                    "latitude": feat_lat,
                    "longitude": feat_lon,
                    "diameter_meters": round(diameter_meters, 1),
                    "diameter_km": diameter_km,
                    "estimated_depth_meters": est_depth_m,
                    "depth_to_diameter_ratio": round(est_depth_m / (diameter_meters + 1e-6), 3),
                    "local_confidence_pct": round(local_conf, 1),
                    "local_hallucination_risk_pct": round(local_risk, 1)
                })
                feature_id += 1

        # Sort features by diameter and confidence
        features.sort(key=lambda f: (f["local_confidence_pct"] * 0.5 + f["diameter_meters"] * 0.5), reverse=True)
        return features[:35]

    def annotate_image(self, enhanced_img: np.ndarray, features: list) -> np.ndarray:
        """Draw scientific bounding circles and telemetry labels onto the image."""
        if len(enhanced_img.shape) == 2:
            annotated = cv2.cvtColor(enhanced_img, cv2.COLOR_GRAY2BGR)
        else:
            annotated = enhanced_img.copy()

        for feat in features[:15]: # Show top 15 features
            cx, cy, r = feat["pixel_x"], feat["pixel_y"], feat["pixel_radius"]
            conf = feat["local_confidence_pct"]
            
            # Color code by confidence: Cyan/Green for high, Amber for medium, Red for low
            if conf >= 80.0:
                color = (0, 220, 255) # Cyan (BGR)
            elif conf >= 60.0:
                color = (0, 180, 255) # Amber
            else:
                color = (0, 100, 255) # Orange/Red
                
            # Draw circle rim
            cv2.circle(annotated, (cx, cy), r, color, 2)
            cv2.circle(annotated, (cx, cy), 3, (0, 255, 120), -1) # Center point
            
            # Label
            label_text = f"{feat['id']} ({feat['diameter_km']}km | {conf:.0f}%)"
            cv2.putText(annotated, label_text, (cx - r, max(15, cy - r - 6)), cv2.FONT_HERSHEY_SIMPLEX, 0.42, color, 1, cv2.LINE_AA)

        return annotated
